import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage, Section } from "@/components/legal/legal-page";
import { GITHUB_REPO_URL } from "@/lib/constants";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms under which Codexa is provided.",
};

export default function Page() {
  return (
    <LegalPage title="Terms of Service" updated="April 28, 2026">
      <p>
        Welcome to <strong className="text-foreground">Codexa</strong>. These terms govern your use of
        the Codexa website, GitHub App, and any related services (collectively, the
        &quot;Service&quot;). By installing the bot or signing in, you agree to these terms.
      </p>

      <Section title="1. About the service">
        <p>
          Codexa is a free, open-source AI code review bot for GitHub pull requests. The source code is
          available on{" "}
          <Link href={GITHUB_REPO_URL} target="_blank" rel="noopener" className="text-primary hover:underline">
            GitHub
          </Link>
          {" "}under the MIT License. Codexa is provided as-is, with no service-level guarantees.
        </p>
      </Section>

      <Section title="2. Acceptable use">
        <p>You agree to use the Service only for lawful purposes. You will not:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Use the Service to generate, review, or analyze content that violates any applicable law or third-party rights.</li>
          <li>Attempt to abuse, overload, or circumvent the Service&apos;s rate limits.</li>
          <li>Reverse-engineer, scrape, or impersonate the Service in a way that misleads users.</li>
          <li>Use the Service for code intended to harm others, including malware or unauthorized access tools.</li>
        </ul>
      </Section>

      <Section title="3. AI-generated content">
        <p>
          Reviews posted by Codexa are generated by third-party large language models (currently
          Google Gemini and Groq Llama). These suggestions are <strong className="text-foreground">advisory only</strong>{" "}
          and may contain errors, hallucinations, or miss real issues. You remain solely responsible
          for the code you ship. Codexa is not a substitute for human review, testing, or judgment.
        </p>
      </Section>

      <Section title="4. GitHub App permissions">
        <p>
          When you install Codexa, you grant the GitHub App read access to your pull request diffs and
          permission to post comments on your pull requests. Codexa never modifies your repository
          contents, branches, or settings. You can revoke access at any time by uninstalling the App
          from your GitHub settings.
        </p>
      </Section>

      <Section title="5. Third-party services">
        <p>
          The Service relies on third-party providers, including GitHub, Google Gemini, Groq, Supabase,
          Vercel, and Render. Their respective terms and privacy policies apply to data they handle. We
          are not responsible for outages, data breaches, or policy changes by these providers.
        </p>
      </Section>

      <Section title="6. No warranties">
        <p>
          The Service is provided &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; without warranties of any kind, express
          or implied, including merchantability, fitness for a particular purpose, and non-infringement.
          We do not warrant that the Service will be uninterrupted, error-free, or that AI-generated
          reviews will be accurate.
        </p>
      </Section>

      <Section title="7. Limitation of liability">
        <p>
          To the maximum extent permitted by law, Codexa, its maintainers, and contributors are not
          liable for any indirect, incidental, special, consequential, or punitive damages arising out
          of or in connection with your use of the Service — including loss of code, data, revenue,
          reputation, or business — even if advised of the possibility of such damages.
        </p>
      </Section>

      <Section title="8. Changes to these terms">
        <p>
          We may update these terms occasionally. The &quot;Last updated&quot; date at the top reflects the
          most recent change. Continued use of the Service after an update constitutes acceptance of the
          new terms.
        </p>
      </Section>

      <Section title="9. Contact">
        <p>
          Questions or concerns? Open an issue on{" "}
          <Link href={GITHUB_REPO_URL} target="_blank" rel="noopener" className="text-primary hover:underline">
            our GitHub repository
          </Link>
          {" "}or contact{" "}
          <Link href="https://techymk.vercel.app/" target="_blank" rel="noopener" className="text-primary hover:underline">
            techyMk
          </Link>.
        </p>
      </Section>
    </LegalPage>
  );
}
